name: Designite Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-designite:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Download DesigniteJava
      run: |
        curl -L -o designite.zip https://designite-tools.com/assets/DesigniteJava.jar
        unzip designite.zip -d DesigniteJava

    - name: Run DesigniteJava analysis
      run: |
        java -jar "C:\Users\20211164\Desktop\Projekt Galaxy\DesigniteJava.jar" -ci \
          --Host github.com \
          --Key ${{ secrets.D_KEY }} \
          --PAT ${{ secrets.PAT }} \
          --Repository demoniclove/PlikiJava \
          --Output ${{ github.workspace }}/designite-output \
          --DisableTelemetry

    - name: Upload Designite output
      uses: actions/upload-artifact@v3
      with:
        name: designite-output
        path: ${{ github.workspace }}/designite-output
